site_name: BedquiltDB Docs
theme: readthedocs
docs_dir: doc
pages:
  - 'Home': 'index.md'
  - 'User Guide':
    - 'BedquiltDB Guide': 'guide/index.md'
    - 'Installation': 'guide/installation.md'
    - 'Quick-Start With Docker': 'guide/quick_start.md'
    - 'Conceptual Overview': 'guide/overview.md'
    - 'Clients': 'guide/clients.md'
    - 'Database Operations': 'guide/database_ops.md'
    - 'Constraints': 'guide/constraints.md'
    - 'Reading Data': 'guide/reading_data.md'
    - 'Writing Data': 'guide/writing_data.md'
    - 'Updating BedquiltDB': 'guide/updating.md'
  - 'Spec': 'spec.md'
  - 'Core API': 'api_docs.md'
